using MyScript;

public class Program
{
    public static void Main(string[] args)
    {
        var test = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";
        var input = Seeder.DaySeven();
        var result = DaySevenSolutions.SolvePartTwo(input);
    }
}
